= ps2j - PubSub To JSON

A very narrowly scoped sample project to extract escaped JSON data and take care of some message routing.


== Challenge

Using the Confluent managed GCP PubSub Source connector, messages come as JSON with two keys: `MessageData` and `AttributesMap`:

[src,json]
----
{
  "MessageData": "{  \"Id\": \"7\",  \"FirstName\": \"Samuel\",  \"LastName\": \"Horwitz\",  \"Nickname\": \"Shemp\",  \"Salary\": \"120\",  \"IngestionTime\": \"1991-01-01T00:00:00\"}",
  "AttributesMap": {}
}
----

The "value" of the message has been quote-escaped.
Trying to forward the contents of the original message results in forwarding the entire escaped string.


This project has two main goals:

. Unpack the escaped `MessageData` and make available to other consumers
. Allow for a discriminator key inside the message so that content-based routing to standalone topics may be done





== Sample Data

For this project, some Three Stooges data will serve as a test bed:

[src,json]
----
{  "Id": "2",  "FirstName": "Moses",  "LastName": "Horwitz",  "Nickname": "Moe",  "Salary": "100",  "IngestionTime": "1970-01-01T00:00:00"}
{  "Id": "2",  "FirstName": "Moses",  "LastName": "Horwitz",  "Nickname": "Moe",  "Salary": "110",  "IngestionTime": "1984-01-01T00:00:00"}
{  "Id": "2",  "FirstName": "Moses",  "LastName": "Horwitz",  "Nickname": "Moe",  "Salary": "130",  "IngestionTime": "1999-01-01T00:00:00"}
{  "Id": "3",  "FirstName": "Louis",  "LastName": "Feinberg",  "Nickname": "Larry",  "Salary": "100",  "IngestionTime": "1970-01-01T00:00:00"}
{  "Id": "3",  "FirstName": "Louis",  "LastName": "Feinberg",  "Nickname": "Larry",  "Salary": "115",  "IngestionTime": "1984-01-01T00:00:00"}
{  "Id": "5",  "FirstName": "Jerome",  "LastName": "Horwitz",  "Nickname": "Curly",  "Salary": "100",  "IngestionTime": "1970-01-01T00:00:00"}
{  "Id": "5",  "FirstName": "Jerome",  "LastName": "Horwitz",  "Nickname": "Curly",  "Salary": "112",  "IngestionTime": "1982-01-01T00:00:00"}
{  "Id": "5",  "FirstName": "Jerome",  "LastName": "Horwitz",  "Nickname": "Curly",  "Salary": "133",  "IngestionTime": "1987-01-01T00:00:00"}
{  "Id": "5",  "FirstName": "Jerome",  "LastName": "Horwitz",  "Nickname": "Curly",  "Salary": "145",  "IngestionTime": "1995-01-01T00:00:00"}
{  "Id": "7",  "FirstName": "Samuel",  "LastName": "Horwitz",  "Nickname": "Shemp",  "Salary": "100",  "IngestionTime": "1970-01-01T00:00:00"}
{  "Id": "7",  "FirstName": "Samuel",  "LastName": "Horwitz",  "Nickname": "Shemp",  "Salary": "120",  "IngestionTime": "1991-01-01T00:00:00"}
----




== Overview

A GCP PubSub topic and subscription exist.

A standard KC source connector pulls messages.

This application reads from one landing topic, transforms the escaped data, and optionally demuxes based on
a JSON path.


[src, text]
----

+-------------------+
|                   |
| GCP PubSub Topic  |
+-------------------+			.
				 |								 +--------------------------+
				 |								 |             		          |
				 |								 |  Landing Topic           |
				 +---------------->|  All sample data msgs    |
			Via KC Source 			 |                          |
			Connector						 +--------------------------+
													               |                      +---------------------+
																				 | 											|           	 	      |
																				 | 											|   Ps2JApplication   |
																				 +--------------------->|    (this app)       |
																				  											|                     |
																																+---------------------+
																																						|
																																						|   					+-------------------------+
																																						+------------>|   TableTopic1	  	   	 	|
																																						|							+-------------------------+
																																					  |							+-------------------------+
																																					  +------------>|   TableTopic2           |
																																					  |							+-------------------------+
																																					  |							+-------------------------+
																																					  +------------>|   TableTopicN           |
																																					  |							+-------------------------+
																																					  |							+-------------------------+
																																					  +------------>|   SinkTopic             |
																																					   							+-------------------------+

----

In this sample, we demux on the value of the `FirstName` key.
We demux messages for Moe and Larry into their own topics.
There is also a general sink topic where *all* messages go.

The configuration is all in `application.properties` and should be self explanatory.

